sudo: required

services:
  - docker


before_install:
  - docker build -t alabianca/rapi-web-dev -f Dockerfile.dev .

script:
  - docker run alabianca/rapi-web-dev npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox