sudo: required

services:
  - docker


before_install:
  - docker build -t alabianca/rapi-web-dev -f Dockerfile.dev .

script:
  # run unit tests
  - docker run alabianca/rapi-web-dev npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox

deploy:
  provider: heroku
  api_key:
    secure: "$HEROKU_TOKEN"
  app: "$HEROKU_APP_NAME"
